spring.application.name=libro


spring.jpa.hibernate.ddl-auto=update


spring.datasource.url=jdbc:mysql://localhost:3306/libro_db
spring.datasource.username=root
spring.datasource.password=Kia@4165
spring.jpa.show-sql=true


#mail

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Unwantedme75@gmail.com
spring.mail.password=Kia@4165

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


