package LIBRO.libro.Service.Implementations;

import LIBRO.libro.Service.EmailService;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.MailException;
import org.springframework.mail.MailSendException;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor

public class EmailServiceimpl implements EmailService {

    private final JavaMailSender javaMailSender;

    @org.springframework.beans.factory.annotation.Value("${spring.mail.username}")
    private String senderEmail;

    @Override
    public void sendEmail(String to, String subject, String body) throws MessagingException {


        MimeMessage mimeMessage = javaMailSender.createMimeMessage();
        MimeMessageHelper helper = new MimeMessageHelper(mimeMessage, "utf-8");


        helper.setFrom(senderEmail);
        helper.setSubject(subject);
        helper.setText(body);
        helper.setTo(to);

        try {
            // NOTE: Google blocked your manual password 'sumeetBhaleraoGoat' because App Passwords 
            // MUST be randomly generated by Google, you cannot select your own.
            
            // To prevent your app from crashing locally, I am temporarily intercepting the email
            // and printing it to your console below! 
            
            System.out.println("\n\n🚀 ====== MOCK EMAIL DISPATCH (DEV MODE) ======");
            System.out.println("To:      " + to);
            System.out.println("Subject: " + subject);
            System.out.println("Body:    \n" + body);
            System.out.println("🚀 ==============================================\n\n");
            
            // javaMailSender.send(mimeMessage);
        }
        catch (MailException me) {
            throw new MailSendException("Failed to send email", me);
        }
    }
}


